## SQL at Scale with Spark SQL

Welcome to the SQL mini project. For this project, you will use the Databricks Platform and work through a series of exercises using Spark SQL. The dataset size may not be too big but the intent here is to familiarize yourself with the Spark SQL interface which scales easily to huge datasets, without you having to worry about changing your SQL queries. 

The data you need is present in the mini-project folder in the form of three CSV files. This data will be imported in Databricks to create the following tables under the __`country_club`__ database.

<br>
1. The __`bookings`__ table,
2. The __`facilities`__ table, and
3. The __`members`__ table.

You will be uploading these datasets shortly into the Databricks platform to understand how to create a database within minutes! Once the database and the tables are populated, you will be focusing on the mini-project questions.

In the mini project, you'll be asked a series of questions. You can solve them using the databricks platform, but for the final deliverable,
please download this notebook as an IPython notebook (__`File -> Export -> IPython Notebook`__) and upload it to your GitHub.

### Creating the Database

We will first create our database in which we will be creating our three tables of interest

In [0]:
%sql 
drop database if exists country_club cascade;
create database country_club;
show databases;

namespace
country_club
default

### Creating the Tables

In this section, we will be creating the three tables of interest and populate them with the data from the CSV files already available to you. 
To get started, first upload the three CSV files to the DBFS as depicted in the following figure

![](https://i.imgur.com/QcCruBr.png)


Once you have done this, please remember to execute the following code to build the dataframes which will be saved as tables in our database

In [0]:
# File location and type
file_location_bookings = "/FileStore/tables/Bookings.csv"
file_location_facilities = "/FileStore/tables/Facilities.csv"
file_location_members = "/FileStore/tables/Members.csv"

file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
bookings_df = (spark.read.format(file_type) 
                    .option("inferSchema", infer_schema) 
                    .option("header", first_row_is_header) 
                    .option("sep", delimiter) 
                    .load(file_location_bookings))

facilities_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_facilities))

members_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_members))

In [0]:
# !pwd
# import os
# os.chdir('/databricks/driver')
# !ls

### Viewing the dataframe schemas

We can take a look at the schemas of our potential tables to be written to our database soon

In [0]:
print('Bookings Schema')
bookings_df.printSchema()
print('Facilities Schema')
facilities_df.printSchema()
print('Members Schema')
members_df.printSchema()

### Create permanent tables
We will be creating three permanent tables here in our __`country_club`__ database as we discussed previously with the following code

In [0]:
permanent_table_name_bookings = "country_club.Bookings"
bookings_df.write.format("parquet").saveAsTable(permanent_table_name_bookings)

permanent_table_name_facilities = "country_club.Facilities"
facilities_df.write.format("parquet").saveAsTable(permanent_table_name_facilities)

permanent_table_name_members = "country_club.Members"
members_df.write.format("parquet").saveAsTable(permanent_table_name_members)

### Refresh tables and check them

In [0]:
%sql
use country_club;
REFRESH table bookings;
REFRESH table facilities;
REFRESH table members;
show tables;

database,tableName,isTemporary
country_club,bookings,false
country_club,facilities,false
country_club,members,false

### Test a sample SQL query

__Note:__ You can use __`%sql`__ at the beginning of a cell and write SQL queries directly as seen in the following cell. Neat isn't it!

In [0]:
%sql
select * from bookings limit 3

bookid,facid,memid,starttime,slots
0,3,1,2012-07-03 11:00:00,2
1,4,1,2012-07-03 08:00:00,2
2,6,0,2012-07-03 18:00:00,2

In [0]:
%sql
select * from facilities limit 3;

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,Tennis Court 1,5.0,25.0,10000,200
1,Tennis Court 2,5.0,25.0,8000,200
2,Badminton Court,0.0,15.5,4000,50

In [0]:
%sql
select * from members limit 3;

memid,surname,firstname,address,zipcode,telephone,recommendedby,joindate
0,GUEST,GUEST,GUEST,0,(000) 000-0000,null,2012-07-01 00:00:00
1,Smith,Darren,"8 Bloomsbury Close, Boston",4321,555-555-5555,null,2012-07-02 12:02:05
2,Smith,Tracy,"8 Bloomsbury Close, New York",4321,555-555-5555,null,2012-07-02 12:08:23

#### Q1: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.

In [0]:
%sql
select name as Facility_Name
from facilities
where membercost = 0;

Facility_Name
Badminton Court
Table Tennis
Snooker Table
Pool Table

####  Q2: How many facilities do not charge a fee to members?

In [0]:
%sql
select count(*)
from facilities
where membercost = 0;

count(1)
4

#### Q3: How can you produce a list of facilities that charge a fee to members, where the fee is less than 20% of the facility's monthly maintenance cost? 
#### Return the facid, facility name, member cost, and monthly maintenance of the facilities in question.

In [0]:
%sql
select facid, name as facility_name, membercost, monthlymaintenance
from facilities
where membercost < monthlymaintenance*0.2;

facid,facility_name,membercost,monthlymaintenance
0,Tennis Court 1,5.0,200
1,Tennis Court 2,5.0,200
2,Badminton Court,0.0,50
3,Table Tennis,0.0,10
4,Massage Room 1,9.9,3000
5,Massage Room 2,9.9,3000
6,Squash Court,3.5,80
7,Snooker Table,0.0,15
8,Pool Table,0.0,15

#### Q4: How can you retrieve the details of facilities with ID 1 and 5? Write the query without using the OR operator.

In [0]:
%sql
select *
from facilities
where facid in (1,5);

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
1,Tennis Court 2,5.0,25.0,8000,200
5,Massage Room 2,9.9,80.0,4000,3000

#### Q5: How can you produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100? 
#### Return the name and monthly maintenance of the facilities in question.

In [0]:
%sql
select name, monthlymaintenance, if(monthlymaintenance > 100, 'expensive', 'cheap') as Facility_Type
from facilities;

name,monthlymaintenance,Facility_Type
Tennis Court 1,200,expensive
Tennis Court 2,200,expensive
Badminton Court,50,cheap
Table Tennis,10,cheap
Massage Room 1,3000,expensive
Massage Room 2,3000,expensive
Squash Court,80,cheap
Snooker Table,15,cheap
Pool Table,15,cheap

#### Q6: You'd like to get the first and last name of the last member(s) who signed up. Do not use the LIMIT clause for your solution.

In [0]:
%sql
select firstname, surname as lastname 
from members
where joindate in (select max(joindate) from members);

firstname,lastname
Darren,Smith

####  Q7: How can you produce a list of all members who have used a tennis court?
- Include in your output the name of the court, and the name of the member formatted as a single column. 
- Ensure no duplicate data
- Also order by the member name.

In [0]:
%sql
select distinct f.name, concat(m.firstname, ' ', m.surname) as membername
from bookings b 
join members m 
  on b.memid = m.memid
join facilities f 
  on b.facid = f.facid
where f.name like 'Tennis Court _'
order by membername;

name,membername
Tennis Court 2,Anne Baker
Tennis Court 1,Anne Baker
Tennis Court 2,Burton Tracy
Tennis Court 1,Burton Tracy
Tennis Court 1,Charles Owen
Tennis Court 2,Charles Owen
Tennis Court 2,Darren Smith
Tennis Court 2,David Farrell
Tennis Court 1,David Farrell
Tennis Court 2,David Jones
Tennis Court 1,David Jones
Tennis Court 1,David Pinker
Tennis Court 1,Douglas Jones
Tennis Court 1,Erica Crumpet
Tennis Court 1,Florence Bader
Tennis Court 2,Florence Bader
Tennis Court 1,GUEST GUEST
Tennis Court 2,GUEST GUEST
Tennis Court 2,Gerald Butters
Tennis Court 1,Gerald Butters
Tennis Court 2,Henrietta Rumney
Tennis Court 1,Jack Smith
Tennis Court 2,Jack Smith
Tennis Court 2,Janice Joplette
Tennis Court 1,Janice Joplette
Tennis Court 2,Jemima Farrell
Tennis Court 1,Jemima Farrell
Tennis Court 1,Joan Coplin
Tennis Court 1,John Hunt
Tennis Court 2,John Hunt
Tennis Court 1,Matthew Genting
Tennis Court 2,Millicent Purview
Tennis Court 2,Nancy Dare
Tennis Court 1,Nancy Dare
Tennis Court 1,Ponder Stibbons
Tennis Court 2,Ponder Stibbons
Tennis Court 1,Ramnaresh Sarwin
Tennis Court 2,Ramnaresh Sarwin
Tennis Court 1,Tim Boothe
Tennis Court 2,Tim Boothe
Tennis Court 2,Tim Rownam
Tennis Court 1,Tim Rownam
Tennis Court 2,Timothy Baker
Tennis Court 1,Timothy Baker
Tennis Court 2,Tracy Smith
Tennis Court 1,Tracy Smith

#### Q8: How can you produce a list of bookings on the day of 2012-09-14 which will cost the member (or guest) more than $30? 

- Remember that guests have different costs to members (the listed costs are per half-hour 'slot')
- The guest user's ID is always 0. 

#### Include in your output the name of the facility, the name of the member formatted as a single column, and the cost.

- Order by descending cost, and do not use any subqueries.

In [0]:
%sql
select f.name, concat(m.firstname, ' ', m.surname) as membername, (if(b.memid = 0, f.guestcost, f.membercost)/0.5 * b.slots) as totalcost
from bookings b
join facilities f
  on b.facid = f.facid
join members m
  on b.memid = m.memid
where ((if(b.memid = 0, f.guestcost, f.membercost)/0.5 * b.slots) > 30) and (b.starttime like '2012-09-14 %')
order by totalcost desc;

name,membername,totalcost
Massage Room 2,GUEST GUEST,640.0
Massage Room 1,GUEST GUEST,320.0
Massage Room 1,GUEST GUEST,320.0
Massage Room 1,GUEST GUEST,320.0
Tennis Court 2,GUEST GUEST,300.0
Tennis Court 1,GUEST GUEST,150.0
Tennis Court 1,GUEST GUEST,150.0
Tennis Court 2,GUEST GUEST,150.0
Squash Court,GUEST GUEST,140.0
Massage Room 1,Jemima Farrell,79.2
Squash Court,GUEST GUEST,70.0
Squash Court,GUEST GUEST,70.0
Tennis Court 2,David Jones,60.0
Tennis Court 2,Tim Boothe,60.0
Massage Room 1,Jack Smith,39.6
Massage Room 1,Jemima Farrell,39.6
Massage Room 1,Ponder Stibbons,39.6
Massage Room 2,Florence Bader,39.6
Massage Room 1,Burton Tracy,39.6
Massage Room 1,Matthew Genting,39.6

#### Q9: This time, produce the same result as in Q8, but using a subquery.

In [0]:
%sql
select fname, concat(mfname, ' ', msname) as membername, totalcost
from (
  select f.name as fname, m.firstname as mfname, m.surname as msname, (if(b.memid = 0, f.guestcost, f.membercost)/0.5 * b.slots) as totalcost, b.starttime as bstime
  from bookings b
  join facilities f
    on b.facid = f.facid
  join members m
    on b.memid = m.memid
) as x
where (totalcost > 30) and (bstime like '2012-09-14 %')
order by totalcost desc;

fname,membername,totalcost
Massage Room 2,GUEST GUEST,640.0
Massage Room 1,GUEST GUEST,320.0
Massage Room 1,GUEST GUEST,320.0
Massage Room 1,GUEST GUEST,320.0
Tennis Court 2,GUEST GUEST,300.0
Tennis Court 1,GUEST GUEST,150.0
Tennis Court 1,GUEST GUEST,150.0
Tennis Court 2,GUEST GUEST,150.0
Squash Court,GUEST GUEST,140.0
Massage Room 1,Jemima Farrell,79.2
Squash Court,GUEST GUEST,70.0
Squash Court,GUEST GUEST,70.0
Tennis Court 2,David Jones,60.0
Tennis Court 2,Tim Boothe,60.0
Massage Room 1,Jack Smith,39.6
Massage Room 1,Jemima Farrell,39.6
Massage Room 1,Ponder Stibbons,39.6
Massage Room 2,Florence Bader,39.6
Massage Room 1,Burton Tracy,39.6
Massage Room 1,Matthew Genting,39.6

#### Q10: Produce a list of facilities with a total revenue less than 1000.
- The output should have facility name and total revenue, sorted by revenue. 
- Remember that there's a different cost for guests and members!

In [0]:
%sql
select facilityname, sum(totalcost) as totalrevenue
from (
  select f.name as facilityname, (if(b.memid = 0, f.guestcost, f.membercost)/0.5 * b.slots) as totalcost
  from bookings b
  join facilities f
    on b.facid = f.facid
) as x
-- where totalrevenue < 1000 -- this throws error
group by facilityname
having totalrevenue < 1000
order by totalrevenue desc;

facilityname,totalrevenue
Pool Table,540.0
Snooker Table,480.0
Table Tennis,360.0